//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwManaged.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwManaged.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given coordinates &apos;{0}&apos; are not in the correct format.
        /// </summary>
        internal static string err1_coordinates_error_incorrect_format {
            get {
                return ResourceManager.GetString("err1_coordinates_error_incorrect_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface type expected.
        /// </summary>
        internal static string err2_interface_type_expected {
            get {
                return ResourceManager.GetString("err2_interface_type_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No storage client connection specified in your app.config..
        /// </summary>
        internal static string err3_no_storage_client_connection_specified {
            get {
                return ResourceManager.GetString("err3_no_storage_client_connection_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No universe connection specified in your app.config..
        /// </summary>
        internal static string err4_no_universe_connection_specified {
            get {
                return ResourceManager.GetString("err4_no_universe_connection_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To successfully run a remoting server connection, there must be an authentication storage client connection available..
        /// </summary>
        internal static string err5_remoting_server_connection_error {
            get {
                return ResourceManager.GetString("err5_remoting_server_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the {0} Service in the {1} service manager..
        /// </summary>
        internal static string err6_service_error_not_found {
            get {
                return ResourceManager.GetString("err6_service_error_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service must have a unique technical name in order to run it in the service manager..
        /// </summary>
        internal static string err7_service_error_technical_name {
            get {
                return ResourceManager.GetString("err7_service_error_technical_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the {0} Service to the service manager. A service with an identical technical name already exists..
        /// </summary>
        internal static string service_error_technical_name_unique {
            get {
                return ResourceManager.GetString("service_error_technical_name_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start service {0}, as it&apos;s already running..
        /// </summary>
        internal static string services_error_start {
            get {
                return ResourceManager.GetString("services_error_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t stop service {0}, as it&apos;s currently not running..
        /// </summary>
        internal static string services_error_stop {
            get {
                return ResourceManager.GetString("services_error_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the {0} Service from the {1} services manager, as its currently running please stop the service first..
        /// </summary>
        internal static string services_manager_error_cant_remove_service {
            get {
                return ResourceManager.GetString("services_manager_error_cant_remove_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services manager &apos;{0}&apos; not running..
        /// </summary>
        internal static string services_manager_not_running {
            get {
                return ResourceManager.GetString("services_manager_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service manager must have a unique technical name in order to run it..
        /// </summary>
        internal static string services_manager_technical_name {
            get {
                return ResourceManager.GetString("services_manager_technical_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add an item to a transaction that is comitting..
        /// </summary>
        internal static string transaction_error_add_item {
            get {
                return ResourceManager.GetString("transaction_error_add_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universe connection timed out.
        /// </summary>
        internal static string universe_connection_time_out {
            get {
                return ResourceManager.GetString("universe_connection_time_out", resourceCulture);
            }
        }
    }
}
